//部分正确，有一个点没过 
# include <iostream>                                                                                                                                                                                                                                                                                               
using namespace std;                                                                                                                                                                                                                                                                                               
int main() {                                                                                                                                                                                                                                                                                                       
	bool dealLen(string str);                                                                                                                                                                                                                                                                                         
	bool dealChar(char a);                                                                                                                                                                                                                                                                                            
	int N;                                                                                                                                                                                                                                                                                                            
	cin>>N;                                                                                                                                                                                                                                                                                                           
	string str[N];                                                                                                                                                                                                                                                                                                    
	int i,j,k;                                                                                                                                                                                                                                                                                                        
	for(i=0;i<N;i++) {                                                                                                                                                                                                                                                                                                
		cin>>str[i];                                                                                                                                                                                                                                                                                                     
		if(!dealLen(str[i])){                                                                                                                                                                                                                                                                                            
			cout<<"Your password is tai duan le."<<endl;                                                                                                                                                                                                                                                                          
			continue;                                                                                                                                                                                                                                                                                                       
		}                                                                                                                                                                                                                                                                                                                
		else {                                                                                                                                                                                                                                                                                                           
			int countNum = 0;                                                                                                                                                                                                                                                                                               
			int countWord = 0;      
			int luan = 0;                                                                                                                                                                                                                                                                                        
			for(j=0;j<str[i].length();j++) {                                                                                                                                                                                                                                                                                
				if(!dealChar(str[i][j])) {                                                                                                                                                                                                                                                                                     
					cout<<"Your password is tai luan le."<<endl;
					luan = 1;                                                                                                                                                                                                                                                                        
					break;                                                                                                                                                                                                                                                                                                        
				}else{                                                                                                                                                                                                                                                                                                         
					if((str[i][j]>='A'&& str[i][j]<='Z' ) || (str[i][j]>='a'&&str[i][j]<='z') ) {                                                                                                                                                                                                                                       
						countWord ++;     
                                                                                                                                                                                                                                                                                     
					}                                                                                                                                                                                                                                                                                                             
					if(str[i][j]>='0' && str[i][j] <= '9') {  
					                                                                                                                                                                                                                                                                        
						countNum ++;                                                                                                                                                                                                                                                                                                 
					}                                                                                                                                                                                                                                                                                                             
				} 
				                                                                                                                                                                                                                                                                                                             
			}
			if(luan == 0) {
				if(countWord==0)cout<<"Your password needs zi mu."<<endl;                                                                                                                                                                                                                                                             
				else if(countNum==0) cout<<"Your password needs shu zi."<<endl;                                                                                                                                                                                                                                                       
				else{                                                                                                                                                                                                                                                                                                           
					cout<<"Your password is wan mei."<<endl;                                                                                                                                                                                                                                                                             
				}     
			}
			                                                                                                                                                                                                                                                                                                                  
		                                                                                                                                                                                                                                                                                                                 
			                                                                                                                                                                                                                                                                                                       
		}                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                  
	}	                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                  
bool dealLen(string str) {                                                                                                                                                                                                                                                                                         
	if(str.length()<6) {                                                                                                                                                                                                                                                                                              
		return false;                                                                                                                                                                                                                                                                                                    
	}                                                                                                                                                                                                                                                                                                                 
	return true;                                                                                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                                                                                                  
bool dealChar(char a) {                                                                                                                                                                                                                                                                                            
	if(a=='.' ||( a <= 'Z' && a >= 'A' )|| (a <= 'z' && a >='a') || ( a <= '9' && a>= '0')) {                                                                                                                                                                                                                         
		return true;                                                                                                                                                                                                                                                                                                     
	}                                                                                                                                                                                                                                                                                                                 
	return false;                                                                                                                                                                                                                                                                                                     
}                                                                                                                                                                                                                                                                                                                  